models:
  qwen:
    model: dashscope/qwen3.8-omni-flash
    api_base: https://ws-n7c4pdh4ldno9hkc.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1
    api_key_env: DASHSCOPE_API_KEY
    adapter: default
    params:
      temperature: 0.2
      max_tokens: 8192
      max_retries: 2
      streaming: true
    fallbacks: []
      # - openai
    capabilities:
      supports_tools: true
      supports_parallel_tools: false
      supports_streaming: true
      supports_reasoning: true
      context_window: 128000


  openai:
    model: gpt-5.6-luna
    api_key_env: OPENAI_API_KEY
    adapter: default
    params:
      temperature: 0.2
      max_tokens: 8192
      max_retries: 2
      streaming: true
    fallbacks: []
    capabilities:
      supports_tools: true
      supports_parallel_tools: false
      supports_streaming: true
      supports_reasoning: true
      context_window: 128000

profiles:
  default_coder:
    model: qwen
    tools:
      - list_dir
      - read_file
      - apply_search_replace
      - write_file
      - file_search
      - ripgrep_search
      - execute_command
    prompt: prompts/coder.md

  default_planner:
    model: qwen
    tools:
      - list_dir
      - read_file
      - file_search
      - ripgrep_search
      - submit_plan
      - execute_command
    prompt: prompts/planner.md

  planner:
    model: qwen
    tools:
      - list_dir
      - read_file
      - file_search
      - ripgrep_search
      - submit_plan
      - execute_command
    prompt: prompts/planner.md

  coder:
    model: qwen
    tools:
      - list_dir
      - read_file
      - apply_search_replace
      - write_file
      - file_search
      - ripgrep_search
      - execute_command
    prompt: prompts/coder.md

default_profile: 
  - default_coder
  - default_planner

